{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Given the values of a solution on a coarse grid, this DNN predicts the value of the solution at a particular location.\n",
    "# Essentially, given the values shown by the @ symbol, and a location within the ... region, it will output its\n",
    "# prediction for the value at that location.\n",
    "#\n",
    "#\n",
    "# @   @   @   @   @   @\n",
    "#\n",
    "#\n",
    "#\n",
    "# @   @   @   @   @   @\n",
    "#\n",
    "#       .........\n",
    "#       .       .\n",
    "# @   @ . @   @ . @   @\n",
    "#       .       .\n",
    "#       .       .\n",
    "#       .       .\n",
    "# @   @ . @   @ . @   @\n",
    "#       .       .\n",
    "#       .........\n",
    "#\n",
    "# @   @   @   @   @   @\n",
    "#\n",
    "#\n",
    "#\n",
    "# @   @   @   @   @   @"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "\n",
    "from base import ml"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Set to False to use existing weights for the neural network.\n",
    "# Set to True to continue training the weights from where we left off last time.\n",
    "TRAIN = True"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7599150710>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.75195265, step = 1\n",
      "INFO:tensorflow:global_step/sec: 60.5688\n",
      "INFO:tensorflow:loss = 0.0622496, step = 1001 (16.512 sec)\n",
      "INFO:tensorflow:global_step/sec: 59.6336\n",
      "INFO:tensorflow:loss = 0.10644801, step = 2001 (16.770 sec)\n",
      "INFO:tensorflow:global_step/sec: 59.4441\n",
      "INFO:tensorflow:loss = 0.016690938, step = 3001 (16.822 sec)\n",
      "INFO:tensorflow:global_step/sec: 60.157\n",
      "INFO:tensorflow:loss = 0.027179753, step = 4001 (16.623 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.056762375.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7594099dd8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.054726608, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 13.8754\n",
      "INFO:tensorflow:loss = 0.031529076, step = 6001 (72.072 sec)\n",
      "INFO:tensorflow:global_step/sec: 13.8511\n",
      "INFO:tensorflow:loss = 0.017103761, step = 7001 (72.196 sec)\n",
      "INFO:tensorflow:global_step/sec: 13.7212\n",
      "INFO:tensorflow:loss = 0.02186519, step = 8001 (72.880 sec)\n",
      "INFO:tensorflow:global_step/sec: 13.8542\n",
      "INFO:tensorflow:loss = 0.012755606, step = 9001 (72.181 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.015564528.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596cd2b38>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.012209667, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 6.56311\n",
      "INFO:tensorflow:loss = 0.0059141912, step = 11001 (152.369 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.57432\n",
      "INFO:tensorflow:loss = 0.036410373, step = 12001 (152.106 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.017510174.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596c9e400>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.006123974, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 3.07524\n",
      "INFO:tensorflow:loss = 0.010697847, step = 14001 (325.180 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 14819 into ./saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/517/tvals.npy'\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/530/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/64x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0047915746.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75566e7470>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.9347839, step = 1\n",
      "INFO:tensorflow:global_step/sec: 50.6601\n",
      "INFO:tensorflow:loss = 0.06782167, step = 1001 (19.742 sec)\n",
      "INFO:tensorflow:global_step/sec: 50.9806\n",
      "INFO:tensorflow:loss = 0.075752825, step = 2001 (19.614 sec)\n",
      "INFO:tensorflow:global_step/sec: 50.9031\n",
      "INFO:tensorflow:loss = 0.07197808, step = 3001 (19.645 sec)\n",
      "INFO:tensorflow:global_step/sec: 50.3729\n",
      "INFO:tensorflow:loss = 0.011952376, step = 4001 (19.852 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.09504092.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c8961f60>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.027236514, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 12.494\n",
      "INFO:tensorflow:loss = 0.026152762, step = 6001 (80.040 sec)\n",
      "INFO:tensorflow:global_step/sec: 12.2623\n",
      "INFO:tensorflow:loss = 0.02666597, step = 7001 (81.552 sec)\n",
      "INFO:tensorflow:global_step/sec: 12.8688\n",
      "INFO:tensorflow:loss = 0.0189707, step = 8001 (77.706 sec)\n",
      "INFO:tensorflow:global_step/sec: 13.2434\n",
      "INFO:tensorflow:loss = 0.011764706, step = 9001 (75.510 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.046058603.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75566fc320>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.026325978, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 6.32186\n",
      "INFO:tensorflow:loss = 0.0060478165, step = 11001 (158.183 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.30784\n",
      "INFO:tensorflow:loss = 0.005985369, step = 12001 (158.533 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.006350434.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c8740f60>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.0049443725, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 3.00481\n",
      "INFO:tensorflow:loss = 0.0059707314, step = 14001 (332.801 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 14803 into ./saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/517/tvals.npy'\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/530/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/64x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0041473983.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596a57e48>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.6678632, step = 1\n",
      "INFO:tensorflow:global_step/sec: 51.9528\n",
      "INFO:tensorflow:loss = 0.03545652, step = 1001 (19.251 sec)\n",
      "INFO:tensorflow:global_step/sec: 52.4017\n",
      "INFO:tensorflow:loss = 0.4798862, step = 2001 (19.086 sec)\n",
      "INFO:tensorflow:global_step/sec: 52.3318\n",
      "INFO:tensorflow:loss = 0.21589424, step = 3001 (19.106 sec)\n",
      "INFO:tensorflow:global_step/sec: 52.2753\n",
      "INFO:tensorflow:loss = 0.052541547, step = 4001 (19.142 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.067611836.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c81712e8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.06179624, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 12.8924\n",
      "INFO:tensorflow:loss = 0.010616968, step = 6001 (77.568 sec)\n",
      "INFO:tensorflow:global_step/sec: 13.2286\n",
      "INFO:tensorflow:loss = 0.030017436, step = 7001 (75.593 sec)\n",
      "INFO:tensorflow:global_step/sec: 13.2312\n",
      "INFO:tensorflow:loss = 0.033037826, step = 8001 (75.579 sec)\n",
      "INFO:tensorflow:global_step/sec: 13.0684\n",
      "INFO:tensorflow:loss = 0.03344622, step = 9001 (76.520 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.015520318.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c9143ef0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.011374635, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 6.16953\n",
      "INFO:tensorflow:loss = 0.00556813, step = 11001 (162.092 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.09235\n",
      "INFO:tensorflow:loss = 0.012506349, step = 12001 (164.136 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.012263349.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c87d1ac8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.00857857, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 2.91189\n",
      "INFO:tensorflow:loss = 0.0058919336, step = 14001 (343.421 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 14747 into ./saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/517/tvals.npy'\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/530/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/64x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0053832103.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7599071ac8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.69920826, step = 1\n",
      "INFO:tensorflow:global_step/sec: 50.0578\n",
      "INFO:tensorflow:loss = 0.102850825, step = 1001 (19.979 sec)\n",
      "INFO:tensorflow:global_step/sec: 51.5058\n",
      "INFO:tensorflow:loss = 0.22013524, step = 2001 (19.416 sec)\n",
      "INFO:tensorflow:global_step/sec: 50.3381\n",
      "INFO:tensorflow:loss = 0.0106006805, step = 3001 (19.869 sec)\n",
      "INFO:tensorflow:global_step/sec: 49.8316\n",
      "INFO:tensorflow:loss = 0.031252213, step = 4001 (20.064 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.040792026.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c841dcc0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.042610005, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 12.7458\n",
      "INFO:tensorflow:loss = 0.017653968, step = 6001 (78.459 sec)\n",
      "INFO:tensorflow:global_step/sec: 12.8729\n",
      "INFO:tensorflow:loss = 0.022518259, step = 7001 (77.682 sec)\n",
      "INFO:tensorflow:global_step/sec: 12.7275\n",
      "INFO:tensorflow:loss = 0.025792003, step = 8001 (78.571 sec)\n",
      "INFO:tensorflow:global_step/sec: 12.9887\n",
      "INFO:tensorflow:loss = 0.0118465535, step = 9001 (77.000 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.013661563.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c89b0d30>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.019167818, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 6.11725\n",
      "INFO:tensorflow:loss = 0.021489613, step = 11001 (163.475 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.07101\n",
      "INFO:tensorflow:loss = 0.005902536, step = 12001 (164.717 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.019436847.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c850a400>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.0066976883, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 2.87888\n",
      "INFO:tensorflow:loss = 0.014425865, step = 14001 (347.360 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 14733 into ./saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/517/tvals.npy'\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/532/tvals.npy'\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/531/tvals.npy'\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/528/tvals.npy'\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/535/tvals.npy'\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/529/tvals.npy'\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/530/tvals.npy'\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/534/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/64x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.004103821.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c878f240>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.38766462, step = 1\n",
      "INFO:tensorflow:global_step/sec: 48.5534\n",
      "INFO:tensorflow:loss = 0.06075514, step = 1001 (20.598 sec)\n",
      "INFO:tensorflow:global_step/sec: 49.4978\n",
      "INFO:tensorflow:loss = 0.081627965, step = 2001 (20.203 sec)\n",
      "INFO:tensorflow:global_step/sec: 48.9235\n",
      "INFO:tensorflow:loss = 0.04581582, step = 3001 (20.440 sec)\n",
      "INFO:tensorflow:global_step/sec: 50.08\n",
      "INFO:tensorflow:loss = 0.025439052, step = 4001 (19.971 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.026333712.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596d97518>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.053106792, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 12.553\n",
      "INFO:tensorflow:loss = 0.019603755, step = 6001 (79.667 sec)\n",
      "INFO:tensorflow:global_step/sec: 12.6987\n",
      "INFO:tensorflow:loss = 0.030785773, step = 7001 (78.749 sec)\n",
      "INFO:tensorflow:global_step/sec: 12.4435\n",
      "INFO:tensorflow:loss = 0.020265687, step = 8001 (80.366 sec)\n",
      "INFO:tensorflow:global_step/sec: 12.4535\n",
      "INFO:tensorflow:loss = 0.0065631345, step = 9001 (80.293 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.038241304.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596b735c0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.01832466, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 5.95627\n",
      "INFO:tensorflow:loss = 0.015515266, step = 11001 (167.893 sec)\n",
      "INFO:tensorflow:global_step/sec: 7.51117\n",
      "INFO:tensorflow:loss = 0.0058940407, step = 12001 (133.134 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.01397939.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c87cc588>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.006164987, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 4.27748\n",
      "INFO:tensorflow:loss = 0.0060779443, step = 14001 (233.785 sec)\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/64x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.00709066.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c8901630>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 1.2168669, step = 1\n",
      "INFO:tensorflow:global_step/sec: 72.0676\n",
      "INFO:tensorflow:loss = 0.046940237, step = 1001 (13.878 sec)\n",
      "INFO:tensorflow:global_step/sec: 75.2268\n",
      "INFO:tensorflow:loss = 0.038256697, step = 2001 (13.293 sec)\n",
      "INFO:tensorflow:global_step/sec: 74.7476\n",
      "INFO:tensorflow:loss = 0.053973634, step = 3001 (13.378 sec)\n",
      "INFO:tensorflow:global_step/sec: 75.9927\n",
      "INFO:tensorflow:loss = 0.049979024, step = 4001 (13.159 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.28275248.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596aa22e8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.03518413, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 18.6292\n",
      "INFO:tensorflow:loss = 0.041378137, step = 6001 (53.681 sec)\n",
      "INFO:tensorflow:global_step/sec: 18.825\n",
      "INFO:tensorflow:loss = 0.00909066, step = 7001 (53.120 sec)\n",
      "INFO:tensorflow:global_step/sec: 18.5687\n",
      "INFO:tensorflow:loss = 0.052070707, step = 8001 (53.854 sec)\n",
      "INFO:tensorflow:global_step/sec: 18.6596\n",
      "INFO:tensorflow:loss = 0.02940064, step = 9001 (53.592 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.014324432.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c8245f28>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.015886663, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 9.06366\n",
      "INFO:tensorflow:loss = 0.0086985305, step = 11001 (110.332 sec)\n",
      "INFO:tensorflow:global_step/sec: 9.05727\n",
      "INFO:tensorflow:loss = 0.012972983, step = 12001 (110.408 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.006013779.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c9104ba8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.0056955935, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 4.468\n",
      "INFO:tensorflow:loss = 0.010968029, step = 14001 (223.816 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/128x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.00560358.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c84a75c0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.97272164, step = 1\n",
      "INFO:tensorflow:global_step/sec: 67.4051\n",
      "INFO:tensorflow:loss = 0.65074533, step = 1001 (14.837 sec)\n",
      "INFO:tensorflow:global_step/sec: 68.4704\n",
      "INFO:tensorflow:loss = 0.14834535, step = 2001 (14.605 sec)\n",
      "INFO:tensorflow:global_step/sec: 68.6889\n",
      "INFO:tensorflow:loss = 0.036285937, step = 3001 (14.558 sec)\n",
      "INFO:tensorflow:global_step/sec: 68.2929\n",
      "INFO:tensorflow:loss = 0.024832297, step = 4001 (14.643 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.029441979.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75990e8860>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.017678764, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 17.9255\n",
      "INFO:tensorflow:loss = 0.016938923, step = 6001 (55.788 sec)\n",
      "INFO:tensorflow:global_step/sec: 17.9198\n",
      "INFO:tensorflow:loss = 0.009272616, step = 7001 (55.804 sec)\n",
      "INFO:tensorflow:global_step/sec: 17.4911\n",
      "INFO:tensorflow:loss = 0.012825217, step = 8001 (57.172 sec)\n",
      "INFO:tensorflow:global_step/sec: 17.7318\n",
      "INFO:tensorflow:loss = 0.040452458, step = 9001 (56.395 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.13248158.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c826fda0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.020659806, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 8.78543\n",
      "INFO:tensorflow:loss = 0.0069042277, step = 11001 (113.826 sec)\n",
      "INFO:tensorflow:global_step/sec: 8.6838\n",
      "INFO:tensorflow:loss = 0.050041176, step = 12001 (115.157 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0067176875.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596b63da0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.0057509923, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 4.34961\n",
      "INFO:tensorflow:loss = 0.0067937477, step = 14001 (229.908 sec)\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/128x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0035145124.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596b474e0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.49220723, step = 1\n",
      "INFO:tensorflow:global_step/sec: 55.8987\n",
      "INFO:tensorflow:loss = 0.20269516, step = 1001 (17.891 sec)\n",
      "INFO:tensorflow:global_step/sec: 61.9893\n",
      "INFO:tensorflow:loss = 0.066906214, step = 2001 (16.132 sec)\n",
      "INFO:tensorflow:global_step/sec: 62.3627\n",
      "INFO:tensorflow:loss = 0.024882192, step = 3001 (16.035 sec)\n",
      "INFO:tensorflow:global_step/sec: 62.4059\n",
      "INFO:tensorflow:loss = 0.10607346, step = 4001 (16.024 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.028670562.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c826e668>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.044693347, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 16.7346\n",
      "INFO:tensorflow:loss = 0.050746128, step = 6001 (59.758 sec)\n",
      "INFO:tensorflow:global_step/sec: 16.8891\n",
      "INFO:tensorflow:loss = 0.01249028, step = 7001 (59.209 sec)\n",
      "INFO:tensorflow:global_step/sec: 16.7894\n",
      "INFO:tensorflow:loss = 0.028215919, step = 8001 (59.561 sec)\n",
      "INFO:tensorflow:global_step/sec: 16.5767\n",
      "INFO:tensorflow:loss = 0.019280436, step = 9001 (60.326 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.031634837.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7599147390>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.012625378, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 8.41472\n",
      "INFO:tensorflow:loss = 0.009505084, step = 11001 (118.841 sec)\n",
      "INFO:tensorflow:global_step/sec: 8.40098\n",
      "INFO:tensorflow:loss = 0.01367079, step = 12001 (119.034 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0066557582.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f759406cb70>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.004931544, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 4.17094\n",
      "INFO:tensorflow:loss = 0.006969328, step = 14001 (239.756 sec)\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/128x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0064753583.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c85d20b8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.78820086, step = 1\n",
      "INFO:tensorflow:global_step/sec: 52.1055\n",
      "INFO:tensorflow:loss = 0.07101224, step = 1001 (19.194 sec)\n",
      "INFO:tensorflow:global_step/sec: 54.5608\n",
      "INFO:tensorflow:loss = 0.020502284, step = 2001 (18.328 sec)\n",
      "INFO:tensorflow:global_step/sec: 57.137\n",
      "INFO:tensorflow:loss = 0.025369624, step = 3001 (17.502 sec)\n",
      "INFO:tensorflow:global_step/sec: 57.4098\n",
      "INFO:tensorflow:loss = 0.10133687, step = 4001 (17.419 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.019734189.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f759805c860>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.031033598, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 15.8457\n",
      "INFO:tensorflow:loss = 0.031536605, step = 6001 (63.110 sec)\n",
      "INFO:tensorflow:global_step/sec: 16.0861\n",
      "INFO:tensorflow:loss = 0.018674716, step = 7001 (62.166 sec)\n",
      "INFO:tensorflow:global_step/sec: 15.9021\n",
      "INFO:tensorflow:loss = 0.026933432, step = 8001 (62.886 sec)\n",
      "INFO:tensorflow:global_step/sec: 15.7691\n",
      "INFO:tensorflow:loss = 0.008258522, step = 9001 (63.419 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.05422783.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596b447b8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.017933622, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 7.95133\n",
      "INFO:tensorflow:loss = 0.0056625563, step = 11001 (125.767 sec)\n",
      "INFO:tensorflow:global_step/sec: 7.8234\n",
      "INFO:tensorflow:loss = 0.0030105328, step = 12001 (127.822 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.01839961.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7599107390>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.0049279146, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 3.93833\n",
      "INFO:tensorflow:loss = 0.005805631, step = 14001 (253.916 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/128x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.003242415.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596bb3e10>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.6778182, step = 1\n",
      "INFO:tensorflow:global_step/sec: 51.1558\n",
      "INFO:tensorflow:loss = 0.06504193, step = 1001 (19.550 sec)\n",
      "INFO:tensorflow:global_step/sec: 52.3521\n",
      "INFO:tensorflow:loss = 0.085041426, step = 2001 (19.102 sec)\n",
      "INFO:tensorflow:global_step/sec: 52.4193\n",
      "INFO:tensorflow:loss = 0.029810043, step = 3001 (19.077 sec)\n",
      "INFO:tensorflow:global_step/sec: 52.8582\n",
      "INFO:tensorflow:loss = 0.11597407, step = 4001 (18.918 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.07352662.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596db6cf8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.04706343, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 15.2052\n",
      "INFO:tensorflow:loss = 0.026790828, step = 6001 (65.768 sec)\n",
      "INFO:tensorflow:global_step/sec: 15.0476\n",
      "INFO:tensorflow:loss = 0.07551806, step = 7001 (66.456 sec)\n",
      "INFO:tensorflow:global_step/sec: 14.8307\n",
      "INFO:tensorflow:loss = 0.026922144, step = 8001 (67.427 sec)\n",
      "INFO:tensorflow:global_step/sec: 15.1687\n",
      "INFO:tensorflow:loss = 0.028003704, step = 9001 (65.925 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.03115248.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7599071a90>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.019767297, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 7.69308\n",
      "INFO:tensorflow:loss = 0.010490904, step = 11001 (129.989 sec)\n",
      "INFO:tensorflow:global_step/sec: 7.65341\n",
      "INFO:tensorflow:loss = 0.008873851, step = 12001 (130.661 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.011107944.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c8967d68>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.0073538898, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 3.87155\n",
      "INFO:tensorflow:loss = 0.005862306, step = 14001 (258.297 sec)\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/128x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.004917552.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596b89da0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.62584877, step = 1\n",
      "INFO:tensorflow:global_step/sec: 66.1092\n",
      "INFO:tensorflow:loss = 0.08412118, step = 1001 (15.128 sec)\n",
      "INFO:tensorflow:global_step/sec: 67.7343\n",
      "INFO:tensorflow:loss = 0.17284441, step = 2001 (14.764 sec)\n",
      "INFO:tensorflow:global_step/sec: 68.4647\n",
      "INFO:tensorflow:loss = 0.15321681, step = 3001 (14.606 sec)\n",
      "INFO:tensorflow:global_step/sec: 68.0579\n",
      "INFO:tensorflow:loss = 0.07570573, step = 4001 (14.693 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.108552866.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f759808e8d0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.06394856, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 17.4279\n",
      "INFO:tensorflow:loss = 0.03419508, step = 6001 (57.381 sec)\n",
      "INFO:tensorflow:global_step/sec: 17.2462\n",
      "INFO:tensorflow:loss = 0.029878387, step = 7001 (57.984 sec)\n",
      "INFO:tensorflow:global_step/sec: 17.3616\n",
      "INFO:tensorflow:loss = 0.06325121, step = 8001 (57.599 sec)\n",
      "INFO:tensorflow:global_step/sec: 17.43\n",
      "INFO:tensorflow:loss = 0.033021666, step = 9001 (57.372 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.03391384.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c863ac50>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.039792903, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 8.56717\n",
      "INFO:tensorflow:loss = 0.012282832, step = 11001 (116.727 sec)\n",
      "INFO:tensorflow:global_step/sec: 8.56939\n",
      "INFO:tensorflow:loss = 0.02347311, step = 12001 (116.694 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.010612809.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75566e6128>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.005638979, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 4.26522\n",
      "INFO:tensorflow:loss = 0.019329017, step = 14001 (234.456 sec)\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/256x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0050944607.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7556ecf2b0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 1.8475939, step = 1\n",
      "INFO:tensorflow:global_step/sec: 54.3797\n",
      "INFO:tensorflow:loss = 0.30640417, step = 1001 (18.391 sec)\n",
      "INFO:tensorflow:global_step/sec: 55.2015\n",
      "INFO:tensorflow:loss = 0.12534544, step = 2001 (18.115 sec)\n",
      "INFO:tensorflow:global_step/sec: 55.1722\n",
      "INFO:tensorflow:loss = 0.045102436, step = 3001 (18.125 sec)\n",
      "INFO:tensorflow:global_step/sec: 55.3423\n",
      "INFO:tensorflow:loss = 0.026942138, step = 4001 (18.069 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.06476264.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c8849a58>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.036412843, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 15.653\n",
      "INFO:tensorflow:loss = 0.016858673, step = 6001 (63.888 sec)\n",
      "INFO:tensorflow:global_step/sec: 15.2323\n",
      "INFO:tensorflow:loss = 0.035178594, step = 7001 (65.650 sec)\n",
      "INFO:tensorflow:global_step/sec: 15.4891\n",
      "INFO:tensorflow:loss = 0.038040567, step = 8001 (64.561 sec)\n",
      "INFO:tensorflow:global_step/sec: 15.6663\n",
      "INFO:tensorflow:loss = 0.10177418, step = 9001 (63.832 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.026171684.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f757c7f37f0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.016529404, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 7.80899\n",
      "INFO:tensorflow:loss = 0.004292209, step = 11001 (128.059 sec)\n",
      "INFO:tensorflow:global_step/sec: 7.84799\n",
      "INFO:tensorflow:loss = 0.014573369, step = 12001 (127.421 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.009727359.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596bb39b0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.0054567796, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 3.90651\n",
      "INFO:tensorflow:loss = 0.0069526145, step = 14001 (255.985 sec)\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/256x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.003753235.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596c7ceb8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.43450454, step = 1\n",
      "INFO:tensorflow:global_step/sec: 46.3174\n",
      "INFO:tensorflow:loss = 0.11531559, step = 1001 (21.592 sec)\n",
      "INFO:tensorflow:global_step/sec: 46.5193\n",
      "INFO:tensorflow:loss = 0.13935703, step = 2001 (21.496 sec)\n",
      "INFO:tensorflow:global_step/sec: 46.7741\n",
      "INFO:tensorflow:loss = 0.04985431, step = 3001 (21.379 sec)\n",
      "INFO:tensorflow:global_step/sec: 46.8637\n",
      "INFO:tensorflow:loss = 0.035744164, step = 4001 (21.339 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.084699884.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7594080ef0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.08669147, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 13.7631\n",
      "INFO:tensorflow:loss = 0.19501483, step = 6001 (72.660 sec)\n",
      "INFO:tensorflow:global_step/sec: 14.1144\n",
      "INFO:tensorflow:loss = 0.021816116, step = 7001 (70.850 sec)\n",
      "INFO:tensorflow:global_step/sec: 14.1334\n",
      "INFO:tensorflow:loss = 0.033426095, step = 8001 (70.754 sec)\n",
      "INFO:tensorflow:global_step/sec: 13.9901\n",
      "INFO:tensorflow:loss = 0.03991057, step = 9001 (71.479 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.037022874.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c8226128>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.019376867, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 7.21794\n",
      "INFO:tensorflow:loss = 0.008641506, step = 11001 (138.545 sec)\n",
      "INFO:tensorflow:global_step/sec: 7.18447\n",
      "INFO:tensorflow:loss = 0.0094906315, step = 12001 (139.189 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.006889279.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c8544a20>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.005141509, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 3.58081\n",
      "INFO:tensorflow:loss = 0.0032831016, step = 14001 (279.268 sec)\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/256x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.004861491.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c88ea160>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.7621924, step = 1\n",
      "INFO:tensorflow:global_step/sec: 39.7735\n",
      "INFO:tensorflow:loss = 0.2579301, step = 1001 (25.144 sec)\n",
      "INFO:tensorflow:global_step/sec: 40.6216\n",
      "INFO:tensorflow:loss = 0.1300726, step = 2001 (24.617 sec)\n",
      "INFO:tensorflow:global_step/sec: 40.5004\n",
      "INFO:tensorflow:loss = 0.06264733, step = 3001 (24.692 sec)\n",
      "INFO:tensorflow:global_step/sec: 40.5206\n",
      "INFO:tensorflow:loss = 0.0635555, step = 4001 (24.678 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.02782001.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c81ba5f8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.04499165, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 12.8685\n",
      "INFO:tensorflow:loss = 0.017567907, step = 6001 (77.711 sec)\n",
      "INFO:tensorflow:global_step/sec: 12.6245\n",
      "INFO:tensorflow:loss = 0.103785515, step = 7001 (79.211 sec)\n",
      "INFO:tensorflow:global_step/sec: 12.92\n",
      "INFO:tensorflow:loss = 0.015606731, step = 8001 (77.400 sec)\n",
      "INFO:tensorflow:global_step/sec: 12.8673\n",
      "INFO:tensorflow:loss = 0.015092578, step = 9001 (77.716 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.023607202.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c8858588>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.01993328, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 6.72135\n",
      "INFO:tensorflow:loss = 0.0052843564, step = 11001 (148.782 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.71804\n",
      "INFO:tensorflow:loss = 0.008696519, step = 12001 (148.853 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.008732374.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596ce93c8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.004467409, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 3.3938\n",
      "INFO:tensorflow:loss = 0.005175505, step = 14001 (294.656 sec)\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/256x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.00371314.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75990bee48>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.90519595, step = 1\n",
      "INFO:tensorflow:global_step/sec: 35.2449\n",
      "INFO:tensorflow:loss = 0.102117985, step = 1001 (28.375 sec)\n",
      "INFO:tensorflow:global_step/sec: 35.7003\n",
      "INFO:tensorflow:loss = 0.16923483, step = 2001 (28.011 sec)\n",
      "INFO:tensorflow:global_step/sec: 35.6784\n",
      "INFO:tensorflow:loss = 0.09576006, step = 3001 (28.028 sec)\n",
      "INFO:tensorflow:global_step/sec: 36.0266\n",
      "INFO:tensorflow:loss = 0.05003118, step = 4001 (27.757 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.3521986.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596b73438>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.039637752, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 11.987\n",
      "INFO:tensorflow:loss = 0.027589101, step = 6001 (83.425 sec)\n",
      "INFO:tensorflow:global_step/sec: 11.7883\n",
      "INFO:tensorflow:loss = 0.025993034, step = 7001 (84.830 sec)\n",
      "INFO:tensorflow:global_step/sec: 12.0035\n",
      "INFO:tensorflow:loss = 0.035795867, step = 8001 (83.309 sec)\n",
      "INFO:tensorflow:global_step/sec: 11.9514\n",
      "INFO:tensorflow:loss = 0.05084624, step = 9001 (83.673 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.09381117.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7556f90ef0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.01573528, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 6.30262\n",
      "INFO:tensorflow:loss = 0.010154386, step = 11001 (158.665 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.21622\n",
      "INFO:tensorflow:loss = 0.0073325923, step = 12001 (160.870 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0070026126.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f754e7a6438>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.0054010246, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 3.17469\n",
      "INFO:tensorflow:loss = 0.0107391495, step = 14001 (314.993 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 14901 into ./saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/256x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.009855703.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c86b4da0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 9.425514, step = 1\n",
      "INFO:tensorflow:global_step/sec: 51.9853\n",
      "INFO:tensorflow:loss = 0.3235641, step = 1001 (19.238 sec)\n",
      "INFO:tensorflow:global_step/sec: 52.8726\n",
      "INFO:tensorflow:loss = 0.2691221, step = 2001 (18.914 sec)\n",
      "INFO:tensorflow:global_step/sec: 53.1499\n",
      "INFO:tensorflow:loss = 0.18576145, step = 3001 (18.815 sec)\n",
      "INFO:tensorflow:global_step/sec: 53.3429\n",
      "INFO:tensorflow:loss = 0.027664298, step = 4001 (18.747 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.23623589.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7596c3fa58>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.113637045, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 14.9919\n",
      "INFO:tensorflow:loss = 0.037151255, step = 6001 (66.705 sec)\n",
      "INFO:tensorflow:global_step/sec: 15.3873\n",
      "INFO:tensorflow:loss = 0.068325914, step = 7001 (64.988 sec)\n",
      "INFO:tensorflow:global_step/sec: 15.306\n",
      "INFO:tensorflow:loss = 0.04495406, step = 8001 (65.334 sec)\n",
      "INFO:tensorflow:global_step/sec: 15.2885\n",
      "INFO:tensorflow:loss = 0.11172977, step = 9001 (65.409 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.104868464.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c871e550>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.081516415, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 7.78909\n",
      "INFO:tensorflow:loss = 0.022311129, step = 11001 (128.387 sec)\n",
      "INFO:tensorflow:global_step/sec: 7.70793\n",
      "INFO:tensorflow:loss = 0.0072353696, step = 12001 (129.736 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.009503426.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c90cf400>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.007229084, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 3.81593\n",
      "INFO:tensorflow:loss = 0.010843995, step = 14001 (262.061 sec)\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/512x2_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.004957518.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c8292f60>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 1.912053, step = 1\n",
      "INFO:tensorflow:global_step/sec: 31.4255\n",
      "INFO:tensorflow:loss = 0.091265135, step = 1001 (31.823 sec)\n",
      "INFO:tensorflow:global_step/sec: 32.865\n",
      "INFO:tensorflow:loss = 1.7325549, step = 2001 (30.427 sec)\n",
      "INFO:tensorflow:global_step/sec: 32.9993\n",
      "INFO:tensorflow:loss = 0.06732954, step = 3001 (30.304 sec)\n",
      "INFO:tensorflow:global_step/sec: 33.0864\n",
      "INFO:tensorflow:loss = 0.14769056, step = 4001 (30.223 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.2182783.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c908e320>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.15117636, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 11.4464\n",
      "INFO:tensorflow:loss = 0.03337638, step = 6001 (87.366 sec)\n",
      "INFO:tensorflow:global_step/sec: 11.347\n",
      "INFO:tensorflow:loss = 0.1857431, step = 7001 (88.129 sec)\n",
      "INFO:tensorflow:global_step/sec: 11.4221\n",
      "INFO:tensorflow:loss = 0.102873415, step = 8001 (87.550 sec)\n",
      "INFO:tensorflow:global_step/sec: 11.4441\n",
      "INFO:tensorflow:loss = 0.080162786, step = 9001 (87.381 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.05069698.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c8920940>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.024091125, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 5.96983\n",
      "INFO:tensorflow:loss = 0.009644968, step = 11001 (167.511 sec)\n",
      "INFO:tensorflow:global_step/sec: 5.95848\n",
      "INFO:tensorflow:loss = 0.013734528, step = 12001 (167.828 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.018588593.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f757c7de2b0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.00574291, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 3.06495\n",
      "INFO:tensorflow:loss = 0.0042827176, step = 14001 (326.280 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 14840 into ./saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/512x4_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.005352351.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7546f32e10>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 5.3005433, step = 1\n",
      "INFO:tensorflow:global_step/sec: 24.7491\n",
      "INFO:tensorflow:loss = 0.335495, step = 1001 (40.407 sec)\n",
      "INFO:tensorflow:global_step/sec: 24.7465\n",
      "INFO:tensorflow:loss = 0.09366521, step = 2001 (40.410 sec)\n",
      "INFO:tensorflow:global_step/sec: 23.7184\n",
      "INFO:tensorflow:loss = 0.2512599, step = 3001 (42.161 sec)\n",
      "INFO:tensorflow:global_step/sec: 24.9727\n",
      "INFO:tensorflow:loss = 0.2033875, step = 4001 (40.044 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 1.3228933.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c870ccf8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.11603395, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 9.30874\n",
      "INFO:tensorflow:loss = 0.13987361, step = 6001 (107.428 sec)\n",
      "INFO:tensorflow:global_step/sec: 9.19106\n",
      "INFO:tensorflow:loss = 0.02864296, step = 7001 (108.802 sec)\n",
      "INFO:tensorflow:global_step/sec: 9.19108\n",
      "INFO:tensorflow:loss = 0.105848, step = 8001 (108.800 sec)\n",
      "INFO:tensorflow:global_step/sec: 9.18667\n",
      "INFO:tensorflow:loss = 0.05246677, step = 9001 (108.854 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.28756413.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75567565c0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.14396879, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 4.80314\n",
      "INFO:tensorflow:loss = 0.008539263, step = 11001 (208.200 sec)\n",
      "INFO:tensorflow:global_step/sec: 4.84103\n",
      "INFO:tensorflow:loss = 0.02502438, step = 12001 (206.567 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 12895 into ./saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.014047334.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75c895b2b0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.0059770066, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 2.36411\n",
      "INFO:tensorflow:loss = 0.00546315, step = 14001 (422.994 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 14431 into ./saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/512x6_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0026028906.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75567c89e8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 1.192647, step = 1\n",
      "INFO:tensorflow:global_step/sec: 19.705\n",
      "INFO:tensorflow:loss = 0.15969111, step = 1001 (50.750 sec)\n",
      "INFO:tensorflow:global_step/sec: 19.2062\n",
      "INFO:tensorflow:loss = 0.12701456, step = 2001 (52.067 sec)\n",
      "INFO:tensorflow:global_step/sec: 19.7189\n",
      "INFO:tensorflow:loss = 0.08173098, step = 3001 (50.713 sec)\n",
      "INFO:tensorflow:global_step/sec: 19.7063\n",
      "INFO:tensorflow:loss = 0.3304093, step = 4001 (50.745 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.14898008.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f754d6411d0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.072238654, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 7.61626\n",
      "INFO:tensorflow:loss = 0.07932079, step = 6001 (131.300 sec)\n",
      "INFO:tensorflow:global_step/sec: 7.67835\n",
      "INFO:tensorflow:loss = 0.18779562, step = 7001 (130.236 sec)\n",
      "INFO:tensorflow:global_step/sec: 7.67146\n",
      "INFO:tensorflow:loss = 0.42360997, step = 8001 (130.354 sec)\n",
      "INFO:tensorflow:global_step/sec: 7.61768\n",
      "INFO:tensorflow:loss = 0.19463553, step = 9001 (131.273 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 9590 into ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.058695022.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7556e8c4a8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.119515814, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 4.1535\n",
      "INFO:tensorflow:loss = 0.0151811, step = 11001 (240.763 sec)\n",
      "INFO:tensorflow:global_step/sec: 4.14424\n",
      "INFO:tensorflow:loss = 0.0060793604, step = 12001 (241.298 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 12487 into ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0074191876.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7556ecfcc0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.009632889, step = 13001\n",
      "INFO:tensorflow:global_step/sec: 2.15936\n",
      "INFO:tensorflow:loss = 0.007591667, step = 14001 (463.103 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 14296 into ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/512x8_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.005903746.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7556eafd68>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 3.8075964, step = 1\n",
      "INFO:tensorflow:global_step/sec: 16.7912\n",
      "INFO:tensorflow:loss = 4.5741982, step = 1001 (59.557 sec)\n",
      "INFO:tensorflow:global_step/sec: 16.9611\n",
      "INFO:tensorflow:loss = 1.42589, step = 2001 (58.959 sec)\n",
      "INFO:tensorflow:global_step/sec: 16.9593\n",
      "INFO:tensorflow:loss = 0.48158878, step = 3001 (58.965 sec)\n",
      "INFO:tensorflow:global_step/sec: 16.9659\n",
      "INFO:tensorflow:loss = 0.6506336, step = 4001 (58.941 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 1.7765282.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7556f92e48>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.3914262, step = 5001\n",
      "INFO:tensorflow:global_step/sec: 6.777\n",
      "INFO:tensorflow:loss = 0.21733673, step = 6001 (147.560 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.74192\n",
      "INFO:tensorflow:loss = 0.13940716, step = 7001 (148.326 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.73428\n",
      "INFO:tensorflow:loss = 0.1375178, step = 8001 (148.494 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.70888\n",
      "INFO:tensorflow:loss = 0.03279075, step = 9001 (149.056 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 9042 into ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.30801785.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75940caf98>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt-10000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 10000 into ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.10667746, step = 10001\n",
      "INFO:tensorflow:global_step/sec: 3.62506\n",
      "INFO:tensorflow:loss = 0.01504514, step = 11001 (275.859 sec)\n",
      "INFO:tensorflow:global_step/sec: 3.62298\n",
      "INFO:tensorflow:loss = 0.008662073, step = 12001 (276.016 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 12175 into ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0117634.\n",
      "INFO:tensorflow:Using config: {'_model_dir': './saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 1000, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f75990c96a0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt-13000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Saving checkpoints for 13000 into ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:loss = 0.0075182975, step = 13001\n",
      "INFO:tensorflow:Saving checkpoints for 13854 into ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:global_step/sec: 1.47368\n",
      "INFO:tensorflow:loss = 0.005675654, step = 14001 (678.577 sec)\n",
      "INFO:tensorflow:Error whilst loading FEnicCS solution from save; generating FEniCS solution instead. Error message: [Errno 2] No such file or directory: './fenics_data/525/tvals.npy'\n",
      "INFO:tensorflow:Saving checkpoints for 14998 into ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Saving checkpoints for 15000 into ./saved_models/point_general/512x10_1__ScaleCenterAtPoint_crelu/model.ckpt.\n",
      "INFO:tensorflow:Loss for final step: 0.0057118754.\n"
     ]
    }
   ],
   "source": [
    "### DNN hyperparameters\n",
    "for width in (64, 128, 256, 512):\n",
    "    for depth in (2, 4, 6, 8, 10):\n",
    "        hidden_units = [width] * depth\n",
    "        logits = 1\n",
    "        processor = ml.ScaleCenterAtPoint()\n",
    "        activation=tf.nn.crelu\n",
    "\n",
    "        ### Training hyperparameters #1\n",
    "        drop_rate = 0.0\n",
    "        drop_type = 'dropout'\n",
    "        gradient_clip = 1.0  # May be set to None to turn off gradient clipping\n",
    "\n",
    "        ### Logging/saving hyperparameters\n",
    "        log_steps = 1000  # How many steps to print the current loss.\n",
    "        model_dir_base = './saved_models/point/'\n",
    "        uuid = None\n",
    "        model_dir = ml.model_dir_str(model_dir_base, hidden_units, logits,\n",
    "                                     processor=processor, activation=activation, \n",
    "                                     uuid=uuid)\n",
    "\n",
    "        compile_kwargs = {'gradient_clip': gradient_clip,\n",
    "                          'processor': processor,\n",
    "                          'model_dir': model_dir}\n",
    "        dnn_factory = ml.DNNFactory(hidden_units, logits, drop_rate=drop_rate,\n",
    "                                    drop_type=drop_type, log_steps=log_steps, \n",
    "                                    activation=activation, batch_norm=False,\n",
    "                                    compile_kwargs=compile_kwargs)\n",
    "\n",
    "        max_steps = 0\n",
    "        if TRAIN:\n",
    "            gen_one_data = ml.GenSolutionPoint(fenics_from_save=True)\n",
    "\n",
    "            ### Training hyperparameters #2\n",
    "            batch_size = 32\n",
    "            max_steps += 5000\n",
    "            learning_rate = 0.001\n",
    "            with ml.BatchData.context(gen_one_data=gen_one_data, batch_size=batch_size) as train_input_fn:\n",
    "                dnn = dnn_factory(learning_rate=learning_rate)\n",
    "                dnn.train(input_fn=train_input_fn, max_steps=max_steps)\n",
    "\n",
    "            batch_size = 128\n",
    "            max_steps += 5000\n",
    "            learning_rate = 0.001\n",
    "            with ml.BatchData.context(gen_one_data=gen_one_data, batch_size=batch_size) as train_input_fn:\n",
    "                dnn = dnn_factory(learning_rate=learning_rate)\n",
    "                dnn.train(input_fn=train_input_fn, max_steps=max_steps)\n",
    "\n",
    "            batch_size = 256\n",
    "            max_steps += 3000\n",
    "            learning_rate = 0.0001\n",
    "            with ml.BatchData.context(gen_one_data=gen_one_data, batch_size=batch_size) as train_input_fn:\n",
    "                dnn = dnn_factory(learning_rate=learning_rate)\n",
    "                dnn.train(input_fn=train_input_fn, max_steps=max_steps)\n",
    "\n",
    "            batch_size = 512\n",
    "            max_steps += 2000\n",
    "            learning_rate = 0.00001\n",
    "            with ml.BatchData.context(gen_one_data=gen_one_data, batch_size=batch_size) as train_input_fn:\n",
    "                dnn = dnn_factory(learning_rate=learning_rate)\n",
    "                dnn.train(input_fn=train_input_fn, max_steps=max_steps)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
